services:
  master:
    image: hadoop_base:1.0
    container_name: master
    hostname: master
    user: root
    volumes:
      - master:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - ./conf/local/krb5/client/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    ports:
      - "9870:9870" # hdfs WebUI
      - "8088:8088" #Resource Manager WebUI
    deploy:
      resources:
        limits:
          memory: 1536M
    entrypoint: ["/entrypoint_local.sh", "master"]
    networks:
      hadoop_network:
        ipv4_address: ${local_master_ip}
  
  edgenode:
    image: hadoop_base:1.0
    container_name: edgenode
    hostname: edgenode
    user: root
    volumes:
      - edgenode:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - ./conf/local/krb5/client/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    ports:
      - "18080:18080" #Spark History Server UI
      - "19888:19888" #Mapreduce History Server UI
      - "4040:4040"
      - "4041:4041"
      - "15002:15002"
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - master
    deploy:
      resources:
        limits:
          memory: 2560M
    entrypoint: ["/entrypoint_local.sh", "edgenode"]
    networks:
      hadoop_network:
        ipv4_address: ${local_edgenode_ip}

  worker:
    image: hadoop_base:1.0
    container_name: worker
    hostname: worker
    user: root
    volumes:
      - worker:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - ./conf/local/krb5/client/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    depends_on:
      - master
    deploy:
      resources:
        limits:
          memory: 2560M
    entrypoint: ["/entrypoint_local.sh", "worker"]
    networks:
      hadoop_network:
        ipv4_address: ${local_worker_ip}

  metastore:
    image: mysql:5.7
    container_name: metastore
    environment:
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - metastore:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 384M
    networks:
      hadoop_network:
        ipv4_address: ${local_metastore_ip}

volumes:
  master:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/master
  edgenode:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/edgenode
  worker:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/worker
  metastore:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/metastore
  config_hadoop:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/hadoop
  config_spark:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/spark
  config_hive:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/hive
  config_krb5server:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/krb5/server

networks:
  hadoop_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        
