services:
  master:
    image: ${hadoop_base_image}
    container_name: master
    hostname: master
    user: root
    volumes:
      - master:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - ./conf/local/krb5/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    ports:
      - "9870:9870" # hdfs WebUI
      - "8088:8088" #Resource Manager WebUI
    deploy:
      resources:
        limits:
          memory: ${local_master_memory}
    entrypoint: ["/entrypoint_local.sh", "master"]
    networks:
      hadoop_network:
        ipv4_address: ${local_master_ip}

  worker:
    image: ${hadoop_base_image}
    container_name: worker
    hostname: worker
    user: root
    volumes:
      - worker:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - ./conf/local/krb5/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    ports:
      - "9864:9864"   # DataNode UI
      - "8042:8042"   # NodeManager UI
    depends_on:
      - master
    deploy:
      resources:
        limits:
          memory: ${local_worker_memory}
    entrypoint: ["/entrypoint_local.sh", "worker"]
    networks:
      hadoop_network:
        ipv4_address: ${local_worker_ip}

  metastore:
    image: ${POSTGRES_VERSION}
    container_name: metastore
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./setupScripts/metastore:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: ${local_metastore_memory}
    networks:
      hadoop_network:
        ipv4_address: ${local_metastore_ip}

  edgenode:
    image: ${hadoop_base_image}
    container_name: edgenode
    hostname: edgenode
    user: root
    volumes:
      - edgenode:/var/data/hadoop
      - config_hadoop:/opt/hadoop/etc/hadoop
      - config_spark:/opt/spark/conf
      - config_hive:/opt/hive/conf
      - config_kyuubi:/opt/kyuubi/conf
      # - workspace:/workspace
      - ./conf/local/krb5/krb5.conf:/etc/krb5.conf
      - ./setupScripts/entrypoint_local.sh:/entrypoint_local.sh
    depends_on:
      - master
      - worker
      - metastore
    ports:
      - "15002:15002" # spark-connect-server
      - "10000:10000" # Spark-Thrift-Server
      - "10002:10002"
      - "10009:10009" # KYUUBI JDBC
      - "10099:10099" # KYUUBI REST
      - "8000:8000" # SQLMESH UI Project
    deploy:
      resources:
        limits:
          memory: ${local_edgenode_memory}
    command: ["/entrypoint_local.sh", "edgenode"]
    networks:
      hadoop_network:
        ipv4_address: ${local_edgenode_ip}

volumes:
  master:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/master
  worker:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/worker
  metastore:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/metastore
  edgenode:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./services/local/edgenode
  # workspace:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ${workspace_path}

  config_hadoop:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/hadoop
  config_spark:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/spark
  config_hive:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/hive
  config_kyuubi:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf/local/kyuubi

networks:
  hadoop_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        