[tools]
java = "{% if os() == 'macos' %}zulu-8.92.0.21{% else %}temurin-8.0.482+8{% endif %}"

# [env]
# # Version Definitions

[env]
_.file = ".env"

# Architecture Detection
DOCKER_PLATFORM = "{% if os() == 'macos' %}linux/arm64{% else %}linux/amd64{% endif %}"
IMAGE_ARCH = "{% if os() == 'macos' %}arm64{% else %}amd64{% endif %}"

[tasks.cluster_credir]
description = "Create service directories"
run = '''
{% if os() == "windows" %}
{% set dirs = [
  ".\\services\\cluster\\namenode",
  ".\\services\\cluster\\secondarynamenode",
  ".\\services\\cluster\\resourcemanager",
  ".\\services\\cluster\\worker1",
  ".\\services\\cluster\\worker2",
  ".\\services\\cluster\\worker3",
  ".\\services\\cluster\\historyserver",
  ".\\services\\cluster\\metastore",
  ".\\services\\cluster\\sparkgateway",
  ".\\services\\cluster\\krb5kdc"
] %}
mkdir {{ dirs | join(" ") }}
{% else %}
{% set dirs = [
  "./services/cluster/namenode",
  "./services/cluster/secondarynamenode",
  "./services/cluster/resourcemanager",
  "./services/cluster/worker1",
  "./services/cluster/worker2",
  "./services/cluster/worker3",
  "./services/cluster/historyserver",
  "./services/cluster/metastore",
  "./services/cluster/sparkgateway",
  "./services/cluster/krb5kdc"
] %}
mkdir -p {{ dirs | join(" ") }}
{% endif %}
'''

[tasks.cluster_deldir]
description = "Remove service directories"
run = '''
{% if os() == "windows" %}
{% set dirs = [
  ".\\services\\cluster\\namenode",
  ".\\services\\cluster\\secondarynamenode",
  ".\\services\\cluster\\resourcemanager",
  ".\\services\\cluster\\worker1",
  ".\\services\\cluster\\worker2",
  ".\\services\\cluster\\worker3",
  ".\\services\\cluster\\historyserver",
  ".\\services\\cluster\\metastore",
  ".\\services\\cluster\\sparkgateway",
  ".\\services\\cluster\\krb5kdc"
] %}
rmdir /S /Q {{ dirs | join(" ") }}
{% else %}
{% set dirs = [
  "./services/cluster/namenode",
  "./services/cluster/secondarynamenode",
  "./services/cluster/resourcemanager",
  "./services/cluster/worker1",
  "./services/cluster/worker2",
  "./services/cluster/worker3",
  "./services/cluster/historyserver",
  "./services/cluster/metastore",
  "./services/cluster/sparkgateway",
  "./services/cluster/krb5kdc"
] %}
rm -rf {{ dirs | join(" ") }}
{% endif %}
'''

[tasks.local_credir]
description = "Create service directories"
run = '''
{% if os() == "windows" %}
mkdir \
  .\\services\\local\\master \
  .\\services\\local\\worker \
  .\\services\\local\\edgenode \
  .\\services\\local\\metastore
{% else %}
mkdir -p \
  ./services/local/master \
  ./services/local/worker \
  ./services/local/edgenode \
  ./services/local/metastore
{% endif %}
'''

[tasks.local_deldir]
description = "Remove service directories"
run = '''
{% if os() == "windows" %}
rmdir /S /Q \
  .\\services\\local\\master \
  .\\services\\local\\worker \
  .\\services\\local\\edgenode \
  .\\services\\local\\metastore
{% else %}
rm -rf \
  ./services/local/master \
  ./services/local/worker \
  ./services/local/edgenode \
  ./services/local/metastore
{% endif %}
'''

[tasks.gen_jks]
description = "Generate JKS keystore for Hive"
run = """
keytool -genkeypair \
    -alias thriftserver \
    -keyalg RSA \
    -storetype JKS \
    -keysize 2048 \
    -validity 365 \
    -keystore ./conf/hive/thriftserver.jks \
    -storepass thriftserver \
    -keypass thriftserver \
    -ext SAN=IP:100.84.28.115,DNS:thriftserver \
    -dname "CN=hive.local, OU=Data, O=MyOrg, L=HCM, ST=VN, C=VN"
"""

# Docker commannds
[tasks."docker:build"]
description = "Build base image with version args"
run = [
  '''
  docker buildx build \
    --file ./baseimage/Dockerfile \
    --no-cache \
    --platform {{ env.DOCKER_PLATFORM }} \
    --build-arg ARCHITECTURE={{ env.IMAGE_ARCH }} \
    --build-arg HADOOP_VERSION={{ env.HADOOP_VERSION }} \
    --build-arg SPARK_VERSION={{ env.SPARK_VERSION }} \
    --build-arg HIVE_VERSION={{ env.HIVE_VERSION }} \
    --build-arg KYUUBI_VERSION={{ env.KYUUBI_VERSION }} \
    --build-arg JAVA_VERSION={{ env.JAVA_VERSION }} \
    -t {{ env.hadoop_base_image }} \
    .
  '''
]

[tasks."docker:rebuild"]
description = "Build base image with version args"
run = '''
docker image rm {{ env.hadoop_base_image }} || true

docker buildx build \
  --file ./baseimage/Dockerfile \
  --no-cache \
  --platform {{ env.DOCKER_PLATFORM }} \
  --build-arg ARCHITECTURE={{ env.IMAGE_ARCH }} \
  --build-arg HADOOP_VERSION={{ env.HADOOP_VERSION }} \
  --build-arg SPARK_VERSION={{ env.SPARK_VERSION }} \
  --build-arg HIVE_VERSION={{ env.HIVE_VERSION }} \
  --build-arg KYUUBI_VERSION={{ env.KYUUBI_VERSION }} \
  --build-arg JAVA_VERSION={{ env.JAVA_VERSION }} \
  -t {{ env.hadoop_base_image }} \
  .
'''

[tasks."docker:push_image"]
description = "Push image to dockerhub"
run = "docker push --platform {{ env.DOCKER_PLATFORM }} {{ env.hadoop_base_image }}"


[tasks."docker:start_cluster"]
description = "Start the Hadoop cluster"
run = "docker compose -f docker-compose-cluster.yml -p cluster up"

[tasks."docker:start_cluster_d"]
description = "Start the Hadoop cluster in detached mode"
run = "docker compose -f docker-compose-cluster.yml -p cluster up -d"

[tasks."docker:stop_cluster"]
description = "Stop the Hadoop cluster and remove volumes"
run = "docker compose -p cluster down -v"

[tasks."docker:start_local"]
description = "Start the local container"
run = "docker compose -f docker-compose-local.yml -p local up"

[tasks."docker:stop_local"]
description = "Stop the local container and remove volumes"
run = "docker compose -p local down -v"
