#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

# Example:
# 1. Cluster Core
spark.master                     yarn
spark.submit.deployMode          client
spark.yarn.applicationType       SPARK

# 2. Memory Management (Optimized for Docker)
# In Client mode, the Driver runs in the ThriftServer container RAM
spark.yarn.am.memory             512m
spark.driver.memory              512m
spark.executor.memory            512m
# Helps prevent YARN from killing containers due to overhead
spark.yarn.executor.memoryOverhead 128m

# 3. HDFS & History (Persistence)
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:9000/spark/logs
# Note: Use spark.yarn.archive if you zipped the jars, 
# but for a folder of jars, spark.yarn.jars is correct.
spark.yarn.jars                  hdfs://namenode:9000/spark/jars/*

# 4. History Server (The "Reader" Config)
spark.history.provider           org.apache.spark.deploy.history.FsHistoryProvider
spark.history.fs.logDirectory    hdfs://namenode:9000/spark/logs
spark.history.fs.update.interval 10s
spark.yarn.historyServer.address historyserver:18080

# 5. Shuffle Performance (Production addition)
spark.shuffle.service.enabled           true
spark.dynamicAllocation.enabled         true
spark.shuffle.service.port              7337
spark.dynamicAllocation.minExecutors    1
spark.dynamicAllocation.maxExecutors    10

# 6. Port settings
spark.hadoop.hive.server2.thrift.port        10000
spark.hadoop.hive.server2.use.SSL            false
spark.hadoop.hive.server2.thrift.bind.host   0.0.0.0
spark.hadoop.hive.server2.webui.port         10002
spark.ui.port                                4040
spark.sql.thriftServer.ui.retainedSessions   500
spark.sql.catalogImplementation              hive

# 7. Multi-user Fairness (Crucial!)
# Without this, one big query from User A will block User B entirely.
spark.scheduler.mode                    FAIR

# spark.executor.extraJavaOptions  -XX:+PrintGCDetails -Dkey=value -Dnumbers="one two three"
